const projects = [
    {
      id: 1,
      name: "Moroccan Universities Scopus Analysis",
      github: "https://github.com/ZakariaBenlamkadam/scopus-articles",
      tools: "Azure Blob Storage, SnowFlake, PySpark, DataBricks, PowerBI",
      services: ["Data Analysis", "Data Engineering"],
      year: "2024/2025",
      image: "./images/first.png",
    },
    {
      id: 2,
      name: "MediAi Health Analysis",
      github: "https://github.com/ZakariaBenlamkadam/HealthAI-Patents-Insight",
      tools: "Data Scraping, MongoDB, Snowflake, PySpark, Spark MLlib, NLP , PowerBI, MERN Stack",
      services: ["Data Analysis", "Data Engineering"],
      year: "2023/2024",
      image: "./images/second.png",
    },
    {
      id: 3,
      name: "Morrocan Content Opinion Poll",
      github: "https://github.com/ZakariaBenlamkadam/morrocan-content",
      tools: "GoogleSheet, PowerBI, Data Modeling , DAX, PowerQuery",
      services: ["Data Analysis"],
      year: 2024,
      image: "./images/architecture.png",
    },
    {
      id: 4,
      name: "Sales Management Dashboard",
      github: "https://zakariabenlamkadam.github.io/analysis-project/",
      tools: "PowerBI ,SSMS, SQL",
      services: ["Data Analysis"],
      year: 2023,
      image: "./images/architecture.png",
    },
    {
      id: 5,
      name: "Predict Winning Products for Dropshippers",
      github: "https://github.com/ZakariaBenlamkadam/Classification_Products",
      tools: "Pandas , Numpy, Sickit-learn, NLTK, Feature Engineering, Flask, React",
      services: ["Data Science"],
      year: 2023,
      image: "./images/architecture.png",
    },
    {
      id: 6,
      name: "Dostoevsky-style text generation model",
      github: "https://github.com/ZakariaBenlamkadam/text-generator",
      tools: "PyTorch, RNN, LSTM, ROUGE score, BLEU score.",
      services: ["Data Science"],
      year: 2024,
      image: "./images/architecture.png",
    },
    {
      id: 7,
      name: "Spell checker with an n-gram language model",
      github: "https://github.com/ZakariaBenlamkadam/correcteur-d-orthographe",
      tools: "NLTK, Language Model, re, Tokenisation",
      services: ["Data Science"],
      year: 2024,
      image: "./images/architecture.png",
    },
  ];
  
  export default projects;
  